### ISSUE TITLE
(Question from Oxford Univ) About calculating neuron coverage

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/adapt#6]
When calculating neuron coverage, I had initially expected that each element of the full activation tensor of a layer would be a neuron. However, adapt/network/network.py line 69, you take a tensor of dimensions HxWxC and turn it into a vector of dimension C by flattening and taking the mean of the first two dimensions. I believe DeepXplore does this as well, but I'm not sure I understand why this is?

**Comment by henrylee97** [comment]
Neurons are computational units in the neural networks.
In both fully-connected layer and convolution layer, the last dimension represents the computational units (the reason why is described below).
Therefore, we reduce the dimensions except for the last dimension by averaging them.
* In fully-connected layer, since the output is 1-d vector (when excluding the batch dimension), the last dimension of the output is equal to the number of neurons.
* In convolution layer, the output is calculated by sliding the same kernel across the input; in other words, one kernel is needed to calculate one channel (C) of the output regardless of the size of the inputs (H x W). Therefore, the kernels, which are important computational units, are counted as neurons.
